title: martbetz.github.io
author:
  name: Mart Betz
  email: alt.t9-52qb4et@yopmail.com
description: > # this means to ignore newlines until "show_excerpts:"
  JPEG Junkie: An Affliction of Addiction to Obsessive Observation and the Prevailing Preservation Thereof!
  
show_excerpts: true # set to true to show excerpts on the homepage


include:
  - /086d154f76bf49d3ae51db55a1a3a58d97a55159


paginate: 3  # amount of posts to show per page
# paginate_path: /page:num/
paginate_path: /086d154f76bf49d3ae51db55a1a3a58d97a55159/page:num/


# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%a, %b %-d, %Y"


  # generate social links in footer
  social_links:
#    - { platform: devto,          user_url: "https://dev.to/jekyll" }
#    - { platform: dribbble,       user_url: "https://dribbble.com/jekyll" }
#    - { platform: facebook,       user_url: "https://www.facebook.com/jekyll" }
#    - { platform: flickr,         user_url: "https://www.flickr.com/photos/jekyll" }
#    - { platform: github,         user_url: "https://github.com/jekyll/minima" }
#    - { platform: github,         user_url: "https://github.com/martbetz" }
#    - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=qc6CJjYAAAAJ" }
#    - { platform: instagram,      user_url: "https://www.instagram.com/jekyll" }
#    - { platform: keybase,        user_url: "https://keybase.io/jekyll" }
#    - { platform: linkedin,       user_url: "https://www.linkedin.com/in/jekyll" }
#    - { platform: microdotblog,   user_url: "https://micro.blog/jekyll" }
#    - { platform: pinterest,      user_url: "https://www.pinterest.com/jekyll" }
#    - { platform: stackoverflow,  user_url: "https://stackoverflow.com/users/1234567/jekyll" }
#    - { platform: telegram,       user_url: "https://t.me/jekyll" }
#    - { platform: twitter,        user_url: "https://twitter.com/jekyllrb" }
#    - { platform: youtube,        user_url: "https://www.youtube.com/jekyll" }
#    - { platform: youtube,        user_url: "https://www.m.youtube.com/@martbetz" }


# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - 086d154f76bf49d3ae51db55a1a3a58d97a55159/index.html
 - about.html
# - now.html
 - reference.html
 - archive.html
 - contact.html
# - terms-of-use.html
# - links.html
# - legal.html
# - test.html


# Build settings
theme: minima


plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-paginate
 - jekyll-smartify

